name: Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUBY_VERSION: 2.6.6
  NODE_VERSION: 12.9.1
    
jobs:
  test:
    environment: test
    name: Test
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:11
    #     ports:
    #       - 5432:5432
    #     env:
    #       DATABASE_USERNAME: postgres
    #       DATABASE_PASSWORD: postgres
    #       POSTGRES_HOST_AUTH_METHOD: trust
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      # - name: Setup & create Database
      #   run: |
      #     bundle exec rake decidim:generate_external_test_app
      #     bundle exec rails db:create db:schema:load
      #   env:
      #     RAILS_ENV: test
      #     DATABASE_USERNAME: postgres
      #     DATABASE_PASSWORD: postgres

      # - name: Precompile assets
      #   run: bundle exec rake assets:precompile
      #   env:
      #     RAILS_ENV: test

      - name: Run rake api tests
        run: bundle exec rake civicrm:test:all
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          CIVICRM_TEST_USER_ID: ${{ secrets.CIVICRM_TEST_USER_ID }}
          CIVICRM_TEST_GROUP_NAME: ${{ secrets.CIVICRM_TEST_GROUP_NAME }}
          CIVICRM_VERIFICATION_URL: ${{ secrets.CIVICRM_VERIFICATION_URL }}
          CIVICRM_VERIFICATION_API_KEY: ${{ secrets.CIVICRM_VERIFICATION_API_KEY }}
          CIVICRM_VERIFICATION_SECRET: ${{ secrets.CIVICRM_VERIFICATION_SECRET }}
